### ISSUE TITLE
upload file with filename contain chinese character,request can‘t encode it

### ISSUE THREAD

**Issue by lee20220110** [apache/jmeter#5982] opened 2023-06-14 02:54 UTC
### Expected behavior

when i send request, chinese character can be encode with utf-8,so i can see this filename is correct，but now it can't be encoded

### Actual behavior

![image](https://github.com/apache/jmeter/assets/97431426/4b6ffffa-fdf8-4c83-8808-c2507ebdd599)

POST data:
-----------------------------7d159c1302d0y0
Content-Disposition: form-data; name="file"; filename="????????????????.docx"
Content-Type: application/msword
Content-Transfer-Encoding: binary

<actual file content, not shown here>
-----------------------------7d159c1302d0y0--

[no cookies]

i send a file with chinese character filename ,but i got filename by ????

### Steps to reproduce the problem

1. write request parameter
2. choose method by post
3. send request

### JMeter Version

5.5

### Java Version

java 17.0.7 2023-04-18 LTS

**Comment by vlsi** [comment] 2023-06-14 10:39
Duplicate of https://github.com/apache/jmeter/issues/4546

**Closed by vlsi** 2023-06-14 10:39 UTC
Labels: defect, to-triage
