### ISSUE TITLE
Summary Report and Aggregate report in JMeter s different value for Minimum response time.

### ISSUE THREAD

**Issue by praveshpr** [apache/jmeter#6081] opened 2023-09-21 01:40 UTC
### Expected behavior

If we add any listeners to jmeter, we should get all values intact in every listener.

### Actual behavior

I executed jmeter script via gui mode and noticed that, the min value in both the reports(Summary report & aggregate report ) is different, wears other values were same in both listeners 

### Steps to reproduce the problem

1.Any sample request to jmeter.
2.Add Summary report and Aggregate report listeners to jmeter.
3.Now run the test for 2-3 minute.
4.Now observe results in both listeners.
5.The min value will differ in both listeners

### JMeter Version

5.6.2

### Java Version

1.8.0_271

### OS Version

Windows 11 enterprise 22h2

**Comment by Ninja-Cyborg** [comment] 2023-10-19 01:32
You are right. I ran the tests; min column values were all zeroes.
It occurred in case of Summary Report listener (JMeter 5.6.2). However, Version 5.5 worked fine.

**Comment by FSchumacher** [comment] 2023-10-25 14:50
Looks like a duplicate of #6043 
Feel free to re-open, if you think that this is a different issue.

**Closed by FSchumacher** 2023-10-25 14:50 UTC
Labels: defect, to-triage
