### ISSUE TITLE
Special characters in file name are replaced by "?" in HTTP Request Sampler

### ISSUE THREAD

**Issue by user412857** [apache/jmeter#5758] opened 2023-01-10 15:02 UTC
### Expected behavior

HTTP Request Sampler should allow upload of files which name contains special characters, without changing the files name.

### Actual behavior

In HTTP Request Sampler, when uploading a file which name contains special characters (for example: éèà), the characters are replaced by "?" in HTTP Request:

> Content-Disposition: form-data; name="file1"; filename="nameWithSpecialCharacters_??.txt" Content-Type: text/plain Content-Transfer-Encoding: binary

This is when we use HttpClient4 implementation. With java implementation, they are replaced by "�" (REPLACEMENT CHARACTER).

Note that setting `file.encoding` system property to `UTF-8` doesn't affect the behavior.

### Steps to reproduce the problem

1. Add HTTP Request in TestPlan.
2. Select the POST method.
3. Type in the Path.
4. Select use multipart/form-data.
5. Under the File Upload tab, enter the file path, Parameter Name, and MimeType. MIME Type examples: image/jpeg, image/png, text/plain. Choose a file which name contains special characters (for example: éèà)
6. Save and run the test.
7. In View Results Tree, Request Body, check that special characters are replaced by "?" or "�".

### JMeter Version

5.5

### Java Version

java version "11.0.13" 2021-10-19 LTS

### OS Version

Microsoft Windows [Version 10.0.19044.2364]

**Comment by vlsi** [comment] 2023-05-20 06:38
The syntax is to send the filename twice: https://greenbytes.de/tech/webdav/rfc5987.html#examples

We probably need implementing it

**Comment by vlsi** [comment] 2023-06-14 10:40
Duplicate of https://github.com/apache/jmeter/issues/4546

**Closed by vlsi** 2023-06-14 10:40 UTC
Labels: enhancement, help-wanted

**Comment by user412857** [comment] 2023-06-14 14:51
> The syntax is to send the filename twice: https://greenbytes.de/tech/webdav/rfc5987.html#examples
> 
> We probably need implementing it

Can you be more explicit?

**Comment by vlsi** [comment] 2023-06-14 14:55
This is a duplicate of https://github.com/apache/jmeter/issues/4546. Let us please discuss in https://github.com/apache/jmeter/issues/4546
