### ISSUE TITLE
NOT Able to End the Test and Generate Report after One Hour Execution in NON GUI Mode

### ISSUE THREAD

**Issue by asfimport** [apache/jmeter#5691] opened 2022-07-20 08:28 UTC
**Munnangi Manikanta Reddy** ([Bug 66172](https://bz.apache.org/bugzilla//show_bug.cgi?id=66172&redirect=false)):
NOT Able to End the Test and Generate Report after One Hour Execution in NON GUI Mode

SYSTEM Config : 4cpus - 16gb RAM 
disk - 32 GB
OS : Linux

we are Running for 100 users on 2 different machines (50 Each)

Created attachment [MicrosoftTeams-image%20%2853%29.png](https://apache.github.io/jmeter-bugzilla-attachments/72/66172/38340/MicrosoftTeams-image%2520%252853%2529.png): This is How it hangs after 1 hour of execution

<img src='https://apache.github.io/jmeter-bugzilla-attachments/72/66172/38340/MicrosoftTeams-image%2520%252853%2529.png' alt='This is How it hangs after 1 hour of execution'>

Severity: normal
OS: Linux

**Comment by mauritz-lovgren** [comment] 2023-06-29 07:40
Having same issue running latest version of JMeter on OpenJDK 64-Bit Server VM version 17.0.2+8-86 installed on Mac Ventura 13.4.1 using brew.

When running in UI mode, the tests finish as expected, but when running in non-ui mode (using the -n flag during startup), the test continues forever:

> Starting JMeter in non-UI mode (runs test suite automatically)
> WARNING: package sun.awt.X11 not in java.desktop
> WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
> WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
> WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
> WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
> Creating summariser <summary>
> Created the tree successfully using loadtest.jmx
> Starting standalone test @ 2023 Jun 29 09:35:56 CEST (1688024156520)
> Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
> summary +      5 in 00:00:04 =    1.4/s Avg:    62 Min:    47 Max:   107 Err:     0 (0.00%) Active: 1 Started: 1 Finished: 0
> summary +     37 in 00:00:30 =    1.2/s Avg:    57 Min:    11 Max:   117 Err:     0 (0.00%) Active: 1 Started: 1 Finished: 0
> summary =     42 in 00:00:34 =    1.2/s Avg:    58 Min:    11 Max:   117 Err:     0 (0.00%)
> summary +     38 in 00:00:30 =    1.3/s Avg:    81 Min:    11 Max:   243 Err:     0 (0.00%) Active: 1 Started: 1 Finished: 0
> summary =     80 in 00:01:04 =    1.3/s Avg:    69 Min:    11 Max:   243 Err:     0 (0.00%)
> 

The test scenario in this example takes about 30 seconds to execute in UI mode, hangs forever in non-UI mode.

The JMX file has connection and response timeout set for all samplers, and those work as expected in UI mode.

**Comment by vlsi** [comment] 2023-06-29 08:02
@mauritz-lovgren , Could you try JMeter 5.6.1? (see https://ci-builds.apache.org/job/JMeter/job/JMeter-trunk/ )
I am afraid your case might be a duplicate of https://github.com/apache/jmeter/issues/6008

**Comment by vlsi** [comment] 2023-06-29 08:04
The issue description does not have enough information to reproduce and fix it, so I'm closing the issue.

**Closed by vlsi** 2023-06-29 08:04 UTC
Labels: os: Linux, P2, need info

**Comment by mauritz-lovgren** [comment] 2023-06-29 08:22
Thank you, will try 5.6.1! 👍

**Comment by nabanita4015** [comment] 2024-03-18 08:21
Hi Team,
While generating  HTML report in Jmeter I am getting below warning message  because of which I am not able to generate html report from CSV report.
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release.

Could you please help me here? @vlsi @asfimport
