### ISSUE TITLE
Jmeter parameterization caused backslash to be escaped

### ISSUE THREAD

**Issue by silgen** [apache/jmeter#5803] opened 2023-04-14 12:15 UTC
### Steps to reproduce the problem

Previously: When using jmeter for interface testing, the request body was parameterized, and the execution result reported an error. But without parameterization, the execution result is successful, and after parameterization, the parameters read in the request are correct (the parameters at the time of execution failure and success are consistent).
Problem troubleshooting: After parameterization, the two backslashes in the request have become one backslash.
Problem reason: During parameterization, ${} escaped the backslash.
Solution: Replace the single backslash with a double backslash.

Detailed process record reference address：https://www.cnblogs.com/silgen/p/17319290.html

### JMeter Version

5.4.1

### Java Version

jdk1.8.0_151

### OS Version

Windows Feature Experience Pack 1000.22639.1000.0

**Comment by FSchumacher** [comment] 2023-04-15 09:32
Might be the issue #5035

**Comment by wxg0103** [comment] 2023-05-11 10:14
This problem still exists in jmeter5.5, where can I fix it, or can you mention an alternative method?

**Comment by vlsi** [comment] 2023-05-20 05:02
Duplicate of #5035

**Closed by vlsi** 2023-05-20 05:02 UTC
Labels: defect, to-triage
