### ISSUE TITLE
JMeter does not support files with Chinese/Japanese characters

### ISSUE THREAD

**Issue by asfimport** [apache/jmeter#5701] opened 2022-09-05 16:02 UTC
**Ziven** ([Bug 66251](https://bz.apache.org/bugzilla//show_bug.cgi?id=66251&redirect=false)):
It appears hard coded ENCODING with ISO_8859_1 in file 

src/protocol/http/src/main/java/org/apache/jmeter/protocol/http/sampler/PostWriter.java as following:
    public static final String ENCODING = StandardCharsets.ISO_8859_1.name()

Severity: major
OS: Linux

**Comment by vdaburon** [comment] 2022-10-03 15:31
Hi,
I propose a solution to choose how to encode the file name in for a POST Multipart (Java Client implementation)
1) &lt;filename&gt; and use Content encoding = ISO-8859-1 (Don't use Sampler Content encoding)
2) &lt;filename&gt; and use Sampler Content Encoding Value (likes UTF-8 or ISO-8859-15)
3) URLEncoder.encode(&lt;filename&gt;\",&lt;Sampler Content Encoding&gt;\") and use Sampler Content Encoding Value (likes UTF-8 or ISO-8859-15)
4) &lt;filename>; filename*=UTF-8''URLEncoder.encode(&lt;filename&gt;\",UTF-8\") and use Sampler Content Encoding Value= UTF-8 

I think with this list choices, you can POST a file with a correct filename encode

E.g. with filename contains **Greek** Alphabet :
2)  &lt;filename&gt; and use Sampler Content Encoding Value= UTF-8
<pre>
POST http://localhost:8081/test/upload

POST data:
-----------------------------7d159c1302d0y0
Content-Disposition: form-data; name="file1"; filename="Ελλάδα.txt"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
Content-Transfer-Encoding: binary

<actual file content, not shown here>
-----------------------------7d159c1302d0y0--
</pre>
4) &lt;filename&gt;; filename*=UTF-8''URLEncoder.encode(&lt;filename&gt;\",UTF-8\") 
<pre>
POST http://localhost:8081/test/upload

POST data:
-----------------------------7d159c1302d0y0
Content-Disposition: form-data; name="file1"; filename="Ελλάδα.txt; filename*=UTF-8''%CE%95%CE%BB%CE%BB%CE%AC%CE%B4%CE%B1.txt"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
Content-Transfer-Encoding: binary

<actual file content, not shown here>
-----------------------------7d159c1302d0y0--
</pre>

New GUI for Files upload with a ComboBox to choose the filename encode method to use



![HttpRequest_FileUpload_Combobox_greek_filename](https://user-images.githubusercontent.com/1881617/193615464-e7d493aa-212b-40f8-84ea-9ae200c4d16d.png)

**Comment by xyziven** [comment] 2022-10-31 14:06
Thank you @asfimport for the migration and @vdaburon for your proposal!

**Comment by vlsi** [comment] 2023-06-14 10:39
Duplicate of https://github.com/apache/jmeter/issues/4546

**Closed by vlsi** 2023-06-14 10:39 UTC
Labels: os: Linux, P2
